STOCKMARKET_T1__low: 0.51
STOCKMARKET_T1__neutral: 0.13
STOCKMARKET_T1__high: 0.36

STOCKMARKET_T2__low: 0.16
STOCKMARKET_T2__neutral: 0.09
STOCKMARKET_T2__high: 0.75

BTC__mag1: 0.3
ETH__mag1: 0.15
SOL__mag1: 0.05

REG__positive: 0.52
REG__neutral: 0.27
REG__negative: 0.21

PUBLIC_PERCEPTION__positive: 0.4
PUBLIC_PERCEPTION__neutral: 0.1
PUBLIC_PERCEPTION__negative: 0.5

TECHNOLOGY__positive: 0.6
TECHNOLOGY__neutral: 0.35
TECHNOLOGY__negative: 0.05

MA_inputweights: [0.2, 0.3, 0.5]

low_low: 0.25
low: 0.66
neutral: 1
high: 1.5
high_high: 4

inflation: 0.98
investment_amount: 10000
